name: Generate PR documentation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    if: "! github.event.pull_request.draft"
    outputs:
      comments: ${{ steps.generate-comments.outputs.comments }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: pip install gitpython openai

    - name: Generate PR documentation
      id: generate-comments
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        comments=`python ${{ github.workspace }}/.github/workflows/generate_docs.py ${{ github.workspace }}`
        echo $comments
        echo "comments<<EOF" >> $GITHUB_OUTPUT
        echo "$comments" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  add-comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: "! github.event.pull_request.draft"
    needs:
      - generate-docs
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            ${{ needs.generate-docs.outputs.comments }}
